version: "3.9"

services:
  mysql-db:
      image: mysql:8.4
      container_name: mysql-db
      restart: unless-stopped
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_ROOT_PASSWORD:
      ports:
        - "3307:3306"
      volumes:
        - mysql_data:/var/lib/mysql
      networks:
        - pagepals-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
    ports:
      - "8088:80"
    networks:
      - pagepals-net

  mongo-logs:
    image: mongo:6.0
    container_name: mongo-logs
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_logs_data:/data/db
    networks:
      - pagepals-net

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-logs
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8089:8081"
    depends_on:
      - mongo-logs
    networks:
      - pagepals-net

  discovery:
      build:
        context: ./discovery
      ports:
        - "8761:8761"
      networks:
        - pagepals-net

  gateway:
      build:
        context: ./gateway
      ports:
        - "8080:8080"
      networks:
        - pagepals-net

  auth-service:
    build:
      context: ./auth
    container_name: auth-service
    ports:
      - "8081:8081"
    networks:
      - pagepals-net

  user-service:
    build:
      context: ./user
    container_name: user-service
    ports:
      - "8082:8082"
    networks:
      - pagepals-net
    volumes:
    - upload_data:/user/upload

  circle-service:
    build:
      context: ./circle
    container_name: circle-service
    ports:
      - "8083:8083"
    env_file:
      - ./circle/.env
    networks:
      - pagepals-net

  membership-service:
    build:
      context: ./membership
    container_name: membership-service
    ports:
      - "8084:8084"
    networks:
      - pagepals-net

  search-service:
    build:
      context: ./search
    container_name: search-service
    ports:
      - "8085:8085"
    networks:
      - pagepals-net
  
  logs-service:
    build:
      context: ./logs
    container_name: logs-service
    restart: unless-stopped
    ports:
      - "8095:8095"
    depends_on:
      - mongo-logs
    networks:
      - pagepals-net

  front:
    build:
      context: ./pagepals-front
    container_name: pagepals-front
    ports:
      - "4200:80"
    networks:
      - pagepals-net

networks:
  pagepals-net:
    driver: bridge

volumes:
  mysql_data:
  upload_data:
  mongo_logs_data:
