server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/user/**
        - id: circle
          uri: lb://circle
          predicates:
            - Path=/api/circles/**
        - id: circle-books
          uri: lb://circle
          predicates:
            - Path=/api/books/**
        - id: membership
          uri: lb://membership
          predicates:
            - Path=/api/memberships/**
        - id: search
          uri: lb://search
          predicates:
            - Path=/api/search/**
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: PagePalsSuperSecretClePourJwt123456
