server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: user
          uri: http://localhost:8082
          predicates:
            - Path=/api/user-profiles/**
        - id: circle
          uri: http://localhost:8083
          predicates:
            - Path=/api/circles/**
        - id: membership
          uri: http://localhost:8084
          predicates:
            - Path=/api/memberships/**
        - id: search
          uri: http://localhost:8085
          predicates:
            - Path=/api/search/**
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
